<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css2?family=Squada+One&family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="Group 3.css">
  <title>GROUP 3</title>
</head>

<body>
  <nav class="nav">
    <div class="name">THE LOUD HOUSE</div>
    <ul class="navlinks">
      <li><a href="Group 3.phtml">Home</a></li>
      <li><a href="Group 3 projects.phtml">Projects</a></li>
      <li><a href="Group 3 about.phtml">About</a></li>
    </ul>
  </nav>
  
  <div class = "header">
    <h3>Welcome to</h3>
    <hr class = "line">
    <h1>THE LOUD HOUSE</h1>
    <hr class = "line">
    <h3>Where Ideas Get Loud.</h3>
  </div>
  
  <div class = "sec">
    <h4>Explore our Lab Exercises and Meet the Team.</h4>
  </div>
  
  <div class = "theteam">
    <h4>Our Team</h4>
    <div class = "jm">
      <a href = "about.html#jm">
      <img src = "jm.jpeg">
      </a>
      <p>JM</p>
    </div>
    
    <div class = "ange">
      <a href = "about.html#ange">
      <img src = "ange.jpeg">
      </a>
      <p>Angeline</p>
    </div>
    
    <div class = "carl">
      <a href = "about.html#carl">
      <img src = "carl.jpeg">
      </a>
      <p>Carl</p>
    </div>
    
    <div class = "helie">
      <a href = "about.html">
      <img src = "helie.jpeg">
      </a>
      <p>Helie</p>
    </div>
    
    <div class = "jl">
      <a href = "about.html#jl">
      <img src = "jl.jpeg">
      </a>
      <p>Lourenze</p>
    </div>
    
    <div class = "hb">
      <a href = "about.html#hb">
      <img src = "bel.jpg">
      </a>
      <p>Hannah</p>
    </div>
  </div>
  
  <div class = "lin"></div>
  
  <div class = "ourproj">
    <h4>Our Projects</h4>
    <div class = "Lab1">
    <a href = "projects.html#Lab1">
      <img src = "3lab1.jpeg">
    </a>
    <p>Lab Exercise 1</p>
    </div>
    
    <div class = "Lab2">
      <a href = "projects.html#Lab2">
        <img src = "3lab2.jpg">
      </a>
      <p>Lab Exercise 2</p>
    </div>
  </div>
  
  <footer>
    <p>@2026 The Loud House</p>
    <p>BSIT 1B</p>
    <p>Pateros Technological College</p>
  </footer>
  
</body>
</html>