<!DOCTYPE html>
<html>
<link rel="stylesheet" href="Group 1.css">
<body> 
<nav class="navbar">
    <a href="Group 1.phtml">Home</a>
    <a href="#projects">Projects</a>
    <a href="Group 1 about.phtml">About</a>
</nav>

<h1>Our personal Github Accounts</h1>
<div class="choices">
    <a href="https://github.com/ezyk08217-jpg?fbclid=IwY2xjawR7-OtleHRuA2FlbQIxMABicmlkETFWWUJ5cTJ2QjlVdVdER3A2c3J0YwZhcHBfaWQQMjIyMDM5MTc4ODIwMDg5MgABHtCy6euysPEalKXbBPrwmJle4FWAu9ZknyWgdh-xUovCwsJE_gx1npV4LMmf_aem_9J8TeAGsaSQZ3vM9q6ydxQ" class="choice-box">
        <img src="image1.jpg" alt="Option 1">
        <p>Queen Caporas</p>
    </a>

    <a href="https://github.com/robbryantgalinato-cmyk" class="choice-box">
        <img src="image2.jpg" alt="Option 2">
        <p>Rob Bryant Galinato</p>
    </a>
    <a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2FRizarhosedemisa%3Ffbclid%3DIwZXh0bgNhZW0CMTAAYnJpZBExVllCeXEydkI5VXVXREdwNnNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR6rcqQReTauJsHesNZPxAc5vfmyZZ0D3tJ1-7zpCiLg0z-7B6rqmmKuyvqkTA_aem_a1EJRGqwsGrYUF8JQjinrg&h=AUABpFL7J1AwhA_JUhMYAJr8i0rs2tosQZmTM_GTtW6b6jhqxkwJP_YNjXqRQsgb1_-Qj2YQHcm-UKA--K_nOUI0QoP0G6v-Vj5NJP7S5dOq7NV-WVvbC5PqrpNGC3x8f-dHDw" class="choice-box">
        <img src="image3.jpg" alt="Option 3">
        <p>Riza Rhose Demisa</p>
    </a>
    <a href="https://github.com/alger-null" class="choice-box">
        <img src="image4.jpg" alt="Option 4">
        <p>Alger Aranain</p>
    </a>
    <a href="https://github.com/Nor-aynGanoy" class="choice-box">
        <img src="image5.jpg" alt="Option 5">
        <p>Nor-ayn Ganoy</p> 
    </a>
<br>
</div>
</body>
<footer class="footer">
    <p>&copy; Group 1, 2026 Our Website. All rights reserved.</p>
</footer>
</html>