<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css2?family=Squada+One&family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="Group 3 projects.css">
  <title>GROUP 3</title>
</head>

<body>
  <nav class="nav">
    <div class="name">THE LOUD HOUSE</div>
    <ul class="navlinks">
      <li><a href="Group 3.phtml">Home</a></li>
      <li><a href="Group 3 projects.phtml">Projects</a></li>
      <li><a href="Group 3 about.phtml">About</a></li>
    </ul>
  </nav>

  <header class="header">
    <h1>Our Projects</h1>
    <p>Explore our lab exercises and personal websites.</p>
  </header>

  <div class="lab">
    <h2>Lab Exercises</h2>

    <div class="grid">
      <div class="card" id = "lab1">
        <h3>Lab 1</h3>
        <p>Simple Web Page</p>
        <a href="https://hannah-bt.github.io/Lab1_TabiosHannahBel/">Open</a>
      </div>

      <div class="card" id = "lab2">
        <h3>Lab 2</h3>
        <p>Basic HTML</p>
        <a href="https://hannah-bt.github.io/Lab2_TabiosHannahBel/">Open</a>
      </div>
    </div>
  </div>

<div class="indiv">
  <h2>Individual Websites</h2>

  <div class="grid">
    <div class="card">
      <div class="img-circle">
        <img src="jm.jpeg">
      </div>
      <h3>JM</h3>
      <a href="https://jmluber2006-spec.github.io/Activity-1-Finals/">Visit Site</a>
    </div>

    <div class="card">
      <div class="img-circle">
        <img src="ange.jpeg">
      </div>
      <h3>Angeline</h3>
      <a href = "https://angelinebanta-max.github.io/Personal-Profile-page/">Visit Site</a>
    </div>

    <div class="card">
      <div class="img-circle">
        <img src="carl.jpeg">
      </div>
      <h3>Carl</h3>
      <a href="https://carlohwenmartinpascual-maker.github.io/Personal-Profile-Page/">Visit Site</a>
    </div>

    <div class="card">
      <div class="img-circle">
        <img src="helie.jpeg">
      </div>
      <h3>Helie</h3>
      <a href="https://helbert02022007-pixel.github.io/Finals--Activty-1/">Visit Site</a>
    </div>

    <div class="card">
      <div class="img-circle">
        <img src="jl.jpeg">
      </div>
      <h3>Lourenze</h3>
      <a href="https://jctumulak-alt.github.io/FINALS-ACTIVITY1/">Visit Site</a>
    </div>

    <div class="card">
      <div class="img-circle">
        <img src="bel.jpg">
      </div>
      <h3>Hannah</h3>
      <a href="https://hannah-bt.github.io/Finals_Activity1/">Visit Site</a>
    </div>

  </div>
</div>

  <footer>
    <p>@2026 The Loud House</p>
    <p>BSIT 1B</p>
    <p>Pateros Technological College</p>
  </footer>
  
</body>
</html>