<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css2?family=Squada+One&family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="Group 3 about.css">
  <title>GROUP 3</title>
</head>

<body>
  <nav class="nav">
    <div class="name">THE LOUD HOUSE</div>
    <ul class="navlinks">
      <li><a href="Group 3 index.phtml">Home</a></li>
      <li><a href="Group 3 projects.phtml">Projects</a></li>
      <li><a href="Group 3 about.phtml">About</a></li>
    </ul>
  </nav>
  
  <h1 class="title">Our Team</h1>
 
  <div class="team-container">
    <div class="card">
      <div class = "img-circle" id = "jm">
      <img src="jm.jpeg">
      </div>
      <h2>John Mark Luber</h2>
      <p class="short-details">A skilled coffee professional who prepares and serves variety of coffee and espresso.</p>
      <div class="socials">
        <a href="https://github.com/jmluber2006-spec">GitHub</a>
        <a href="https://www.facebook.com/share/1BHSDfGfGx/">Facebook</a>
      </div>
    </div>

    <div class="card">
      <div class = "img-circle" id = "ange">
      <img src="ange.jpeg">
      </div>
      <h2>Angeline Banta</h2>
      <p class="short-details">I am a hardworking student who believes that education is the key to a better future.</p>
      <div class="socials">
        <a href="https://github.com/angelinebanta-max">GitHub</a>
        <a href="https://www.facebook.com/share/1CqHMr4ikC/">Facebook</a>
      </div>
    </div>

    <div class="card">
      <div class = "img-circle" id = "carl">
      <img src="carl.jpeg">
      </div>
      <h2>Carl Ohwen Pascual</h2>
      <p class="short-details">I am a hardworking student, balancing school and a job to support myself.</p>
      <div class="socials">
        <a href="https://github.com/carlohwenmartinpascual-maker">GitHub</a>
        <a href="https://www.facebook.com/carl.pascual.186">Facebook</a>
      </div>
    </div>

    <div class="card">
      <div class = "img-circle" id = "helie">
      <img src="helie.jpeg">
      </div>
      <h2>Helbert Dela Peña</h2>
      <p class="short-details">You can call me Helie for short. A first year student from BSIT 1B.</p>
      <div class="socials">
        <a href="https://github.com/helbert02022007-pixel">GitHub</a>
        <a href="https://www.facebook.com/helbert.delapena.397">Facebook</a>
      </div>
    </div>

    <div class="card">
      <div class = "img-circle" id = "jl">
      <img src="jl.jpeg">
      </div>
      <h2>John Lourenze Tumulak</h2>
      <p class="short-details">I enjoy learning programming language and creating simple and responsive websites.</p>
      <div class="socials">
        <a href="https://github.com/jctumulak-alt">GitHub</a>
        <a href="https://www.facebook.com/share/1LdvQfEm2p/">Facebook</a>
      </div>
    </div>

    <div class="card">
      <div class = "img-circle" id = "hb">
      <img src="bel.jpg">
      </div>
      <h2>Hannah Bel Tabios</h2>
      <p class="short-details">Though IT was never an option for me, I can say that I enjoy coding, and have no regrets.</p>
      <div class="socials">
        <a href="https://github.com/hannah-bt">GitHub</a>
        <a href="https://www.facebook.com/share/1CeC1goHgq/">Facebook</a>
      </div>
    </div>

  </div>

 <footer>
    <p>@2026 The Loud House</p>
    <p>BSIT 1B</p>
    <p>Pateros Technological College</p>
  </footer>
  
</body>
</html>