<!DOCTYPE html>
<html>
<head>
    <title>Group 8 - Our Personal Page</title>
    <style>
        body {
            background: #d1ff94;
            font-family: Times New Roman;
            margin: 0;
        }

        h1 {
            background: #bcfffc;
            width: 70%;
            margin: 40px auto 20px;
            padding: 25px;
            border-radius: 40px;
            text-align: center;
        }

        nav {
            background: #bcfffc;
            text-align: center;
            padding: 10px;
            font-size: 22px;
        }

        nav a {
            text-decoration: none;
            color: black;
            margin: 0 40px;
        }

        nav a:hover {
            text-decoration: underline;
        }

        .box {
            background: #bcfffc;
            width: 75%;
            margin: 50px auto;
            padding: 30px;
        }

        .desc {
            background: #ffffff;
            padding: 10px;
            margin: 10px 0 25px;
            text-align: center;
        }

        h2 {
            font-size: 35px;
        }

        form input {
            width: 100%;
            padding: 8px;
            margin: 5px 0 15px;
        }

        button {
            width: 100%;
            padding: 10px;
            background: rgb(0, 183, 255);
            color: white;
            border: none;
        }
    </style>
</head>

<body>

    <h1>GROUP 8</h1>

    <nav>
        <a href="#">HOME</a>
        <a href="#">ABOUT</a>
        <a href="#">CONTACT</a>
    </nav>

    <div class="box">
        <h2>MEMBERS</h2>

        <h3>Armel jade Tolentino</h3>
        <div class="desc">
            I have a strong interest in music, literature, and dance, and I aspire
            to achieve success while finding happiness in independence.
        </div>

        <h3>Kobe Rivera</h3>
        <div class="desc">
            I am a unique individual with my own thoughts, strengths, and goals in life
        </div>

        <h3>Rea may Reyes</h3>
        <div class="desc">
            I am a soul shaped by life’s lessons, chasing dreams that give meaning to every step I take
        </div>

        <h3>Ronaldo Linganay</h3>
        <div class="desc">
            I believe that life is a journey where dreams give me direction and purpose
        </div>

        <h3>Jhamela Pevidal</h3>
        <div class="desc">
            I see life as a journey full of challenges and opportunities. My dreams guide me forward.
        </div>

        <h2 style="color: rgb(0, 0, 0);">Registration Form</h2>

        <form>
            Name:
            <input type="text">

            Email:
            <input type="email">

            Password:
            <input type="password">

            Birthdate:
            <input type="date">

            Age:
            <input type="number">

            <button>Register</button>
        </form>
    </div>

</body>
</html>