<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>BSIT-1Babies Final Project Website</title>

    <link rel="stylesheet" type="text/css" href="website.css">

    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>

<body>

    <nav>
        <ul>

            <li class="logo">
                <img src="1b logo.png" alt="LOGO">
            </li>

            <li><a href="Group 1.phtml"><i class="fa-solid fa-users"></i> GROUP1</a></li>

            <li><a href="Group 2.phtml">
            <i class="fa-solid fa-users"></i> GROUP2</a></li>

            <li><a href="Group 3.phtml">
            <i class="fa-solid fa-users"></i> GROUP3</a></li>

            <li><a href="Group 4.phtml">
            <i class="fa-solid fa-users"></i> GROUP4</a></li>

            <li><a href="Group 5.phtml">
            <i class="fa-solid fa-users"></i> GROUP5</a></li>

            <li><a href="RegisForm.php">
            <i class="fa-solid fa-users"></i> GROUP6</a></li>

            <li><a href="Group 7.phtml">
            <i class="fa-solid fa-users"></i> GROUP7</a></li>

            <li><a href="Group 8.phtml">
            <i class="fa-solid fa-users"></i> GROUP8</a></li>

        </ul>
    </nav>

    <section class="hero">

        <div class="overlay">

            <h1>BSIT-1B</h1>

            <p>TITINDIG PARA SA PANGARAP</p>

        </div>

    </section>

    <div class="wrapper">

        <div class="section">

            <div class="box-area">

                <h2>Welcome!</h2>

                <p>
                    Welcome to the official website of BSIT - 1B.
                    Explore each group using the navigation menu on the left side. </p>
                <p>
                    2026 BSIT - 1Babies All rights reserved. </p>    

            </div>

        </div>

    </div>

</body>
</html>